name: kafka_protocol
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        rebar3:
          - '3.20.0'
        otp:
          - '26'
          - '25'
        kafka:
          - '2.4'
          - '1.1'
          - '0.11'
    runs-on: ubuntu-20.04
    steps:

    # Setup
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache Hex packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/rebar3/hex/hexpm/packages
        key: ${{ runner.os }}-hex2-${{ hashFiles(format('{0}{1}', github.workspace, '/rebar.lock')) }}
        restore-keys: |
          ${{ runner.os }}-hex2-
    - name: Cache Dialyzer PLTs
      uses: actions/cache@v2
      with:
        path: ~/.cache/rebar3/rebar3_*_plt
        key: ${{ runner.os }}--dialyzer2-${{ hashFiles(format('{0}{1}', github.workspace, '/rebar.config')) }}
        restore-keys: |
          ${{ runner.os }}-dialyzer2-

    # Install Erlang
    - name: Install Erlang/OTP
      uses: erlef/setup-beam@v1
      with:
        version-type: strict
        otp-version: ${{matrix.otp}}
        rebar3-version: ${{matrix.rebar3}}

    # Compile
    - name: Compile
      run: |
        rebar3 do compile, dialyzer, ex_doc, xref

    # Tests
    - name: Run tests
      run: |
          export KAFKA_VERSION=${{ matrix.kafka }}
          make test-env
          make eunit || (cd scripts && docker-compose logs)
